# 공통 costmap 설정

obstacle_range: 2.5     # 장애물 감지 범위 (m)
raytrace_range: 3.0     # 레이저 추적 범위 (m)

# 로봇 크기 (footprint): 네 꼭짓점 좌표
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]

inflation_radius: 0.55  # 로봇 주변 장애물 확장 반경

# 감지에 사용할 센서 정의
observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: laser,     # 센서 프레임명
  data_type: LaserScan,    # 센서 타입
  topic: scan,             # LiDAR 토픽명
  marking: true,           # 장애물 표시
  clearing: true           # 지나간 공간 지우기
}
