# husky_dwa/config/global_costmap_params.yaml
# ────────────────────────────────────────────
global_costmap:
  # 프레임
  global_frame:      odom
  robot_base_frame:  base_link

  # 주기
  update_frequency:  5.0    # [Hz]
  publish_frequency: 1.0    # [Hz]

  # 크기·해상도
  rolling_window:    true   # <- 맵리스이므로 rolling window
  static_map:        false  # <- SLAM/정적맵 사용 안 함
  width:             30.0
  height:            30.0
  resolution:        0.05   # [m]

  # 레이어 구성 (Obstacle + Inflation 두 개면 충분)
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser
  laser: {data_type: PointCloud2, topic: /os1/points, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.5   # [m]
