joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

############################################
#   Diff-drive (odom TF 발행 + PID 포함)   #
############################################
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController

  # 바퀴 조인트
  left_wheel:  ['front_left_wheel',  'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']

  # 물리 파라미터
  wheel_separation: 0.57
  wheel_radius:     0.33

  # TF / 토픽
  base_frame_id:  base_link
  odom_frame_id:  odom
  enable_odom_tf: true
  publish_rate:   50
  cmd_vel_timeout: 0.25

gazebo_ros_control:
  pid_gains:
    front_left_wheel: {p: 10.0, i: 0.01, d: 0.1}
    front_right_wheel: {p: 10.0, i: 0.01, d: 0.1}
    rear_left_wheel: {p: 10.0, i: 0.01, d: 0.1}
    rear_right_wheel: {p: 10.0, i: 0.01, d: 0.1}

