joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

############################################
#   Diff-drive (odom TF 발행 + PID 포함)   #
############################################
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController

  # 바퀴 조인트
  left_wheel:  ['front_left_wheel_joint',  'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']

  # 물리 파라미터
  wheel_separation: 0.57
  wheel_radius:     0.33

  # TF / 토픽
  base_frame_id:  base_link
  odom_frame_id:  odom
  enable_odom_tf: true
  publish_rate:   50
  cmd_vel_timeout: 0.25

  # 간단 PID (Effort interface → 필수)
  # 네 바퀴 모두 동일 게인 예시
  left_wheel_pid:  {p: 50.0, i: 0.0, d: 0.5}
  right_wheel_pid: {p: 50.0, i: 0.0, d: 0.5}

############################################
# (선택) 개별 JointVelocityController 예시 #
############################################
#front_left_wheel_controller:
#  type: effort_controllers/JointVelocityController
#  joint: front_left_wheel_joint
#  pid: {p: 50.0, i: 0.0, d: 0.5}
