# DWAPlannerROS 파라미터

# 속도 설정
max_vel_x: 0.5         # 최대 전진 속도 (m/s)
min_vel_x: 0.0         # 최소 전진 속도 (m/s)
max_vel_theta: 1.0     # 최대 회전 속도 (rad/s)
min_vel_theta: -1.0    # 최소 회전 속도 (rad/s)

# 가속도 제한
acc_lim_x: 1.0         # x축 가속도 제한 (m/s^2)
acc_lim_theta: 1.0     # 회전 가속도 제한 (rad/s^2)

# 시뮬레이션 시간 및 샘플 수
sim_time: 2.0          # 경로 시뮬레이션 시간 (초)
vx_samples: 20         # 전진 속도 샘플 수
vtheta_samples: 40     # 회전 속도 샘플 수

# 비용 함수 설정
path_distance_bias: 32.0     # global path를 따르는 경향
goal_distance_bias: 20.0     # goal에 가까이 가려는 경향
occdist_scale: 0.01          # 장애물과 떨어지려는 경향

# 기타 설정
stop_time_buffer: 0.2        # 멈출 때 필요한 시간 버퍼 (초)
forward_point_distance: 0.325  # 전방 예측 포인트 거리
publish_traj_pc: true        # trajectory를 포인트 클라우드로 퍼블리시
publish_cost_grid_pc: true   # 비용 그리드를 포인트 클라우드로 퍼블리시
