global_frame: odom              # 글로벌 좌표계 (지도 기준)
robot_base_frame: base_link      # 로봇 기준 좌표계
update_frequency: 5.0            # 업데이트 빈도 (Hz)
static_map: false                # 정적 맵 사용 여부 (false = 실시간)
transform_tolerance: 0.5         # TF 변환 허용 시간 오차
