## 장애물 레이저 감지 범위
obstacle_range: 5.0             ## 로봇 주변 5m 이내 장애물을 인식
raytrace_range: 6.0             ## 장애물이 없으면 6m까지 공간 비우기(clear)

## 로봇의 실제 외곽선 (Husky는 약 1m x 0.67m 정도 크기)
footprint: [[-0.5, -0.335], [-0.5, 0.335], [0.5, 0.335], [0.5, -0.335]]
# robot_radius: 0.4             ## footprint와 robot_radius는 동시에 쓰면 안됨. 주석 처리

## 장애물 확장 범위 (Husky 주변에 위험지대 만들기)
inflation_radius: 0.75          ## 장애물 근처 0.75m 이내는 위험영역으로 처리

## 장애물 정보에 사용할 센서 이름들
observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: laser_link      ## 실제 Husky의 laser frame (확인 필요. tf에서 `laser` or `front_laser`)
  data_type: LaserScan
  topic: /scan                  ## 실제 퍼블리시되는 LaserScan 토픽 확인하고 일치시켜야 함
  marking: true                ## 장애물 위치로 표시
  clearing: true               ## 공간 비우기 처리도 가능

